import os

from dotenv import load_dotenv

load_dotenv()

TOKEN_TIBBER = os.getenv("TOKEN_TIBBER")
TOKEN_SMARTTHINGS = os.getenv("TOKEN_SMARTTHINGS")
HOME_ID_TIBBER = os.getenv("HOME_ID_TIBBER")
HEAT_PUMP_DEVICE_ID = os.getenv("HEAT_PUMP_DEVICE_ID")
HEAT_PUMP_MODULE_WATER = os.getenv("HEAT_PUMP_MODULE_WATER")
HEAT_PUMP_MODULE_HEATING = os.getenv("HEAT_PUMP_MODULE_HEATING")
HEAT_PUMP_FLOW_TEMPERATURE_POWER_PRODUCTION = int(
    os.getenv("HEAT_PUMP_FLOW_TEMPERATURE_POWER_PRODUCTION")
)
HEAT_PUMP_FLOW_TEMPERATURE_POWER_CONSUMPTION = int(
    os.getenv("HEAT_PUMP_FLOW_TEMPERATURE_POWER_CONSUMPTION")
)
POWER_PRODUCTION_THRESHOLD = int(os.getenv("POWER_PRODUCTION_THRESHOLD"))
POWER_CONSUMPTION_THRESHOLD = int(os.getenv("POWER_CONSUMPTION_THRESHOLD"))
TRACK_LAST_N_POWER_MEASUREMENTS = int(os.getenv("TRACK_LAST_N_POWER_MEASUREMENTS"))
